config/routes.rb
Shop::Application.routes.draw do
  root :to => 'home#index'

  get 'home/index'
  get 'about/index'
  get 'contact/index'

  post 'add_to_basket/:product_id' => 'baskets#add_to_basket', :as => 'add_to_basket'

  resources :orders
  resources :products
  resources :baskets
  resources :order_positions
  resources :producers
  resources :categories
  resources :payment_methods
  resources :deliveries
  resources :addresses
  resources :countries

  devise_for :users, :controllers => { :sessions => 'sessions' }
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    unless user.has_role? :admin
      unless user.new_record?
        can :manage, [Address, Basket, User, OrderPosition], :user_id => user.id
        can :manage, OrderPosition, :container_id => user.basket.id, :container_type => 'Basket'
        can [:create, :read], Order, :user_id => user.id
      end
      can :read, Category
      can :read, Product
    else
      can :manage, :all
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_one :order
  attr_accessible :address_line_1, :address_line_2, :city, :first_name, :last_name, :postal_code, :country_id, :user_id, :name
  validates :address_line_1, :city, :first_name, :last_name, :postal_code, :country_id, :user_id, :name, :presence => true
  validates_format_of :postal_code, :with => /\d{2}\-\d{3}/
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  has_many :order_positions, :as => :container

  def add_to_basket(product_id)
    op = OrderPosition.where(:product_id => product_id, :container_id => self.id, :container_type => 'Basket').first
    if op.nil?
      op = OrderPosition.new
      op.product_id = product_id
      op.container = self
      op.amount = 1;
      op.price = Product.find(product_id).gross_price
    else
      op.amount += 1
      op.price += Product.find(product_id).gross_price
    end
    op.save
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  acts_as_nested_set
  has_many :products
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  has_many :addresses
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :cost, :name
  has_one :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :address
  belongs_to :delivery
  belongs_to :payment_method
  belongs_to :user
  has_many :order_positions, :as => :container
  attr_accessible :delivery_cost, :status, :value, :address_id, :delivery_id, :payment_method_id
  validate :available
  validates :address_id, :presence => true

  private
    def available
      order_positions.each do |op|
        if op.amount > op.product.availability
          errors.add(:base, 'order positions must be available')
        end
      end
    end
end

app/models/order_position.rb
class OrderPosition < ActiveRecord::Base
  belongs_to :product
  belongs_to :container, :polymorphic => true
  attr_accessible :amount, :price
  validates :amount, :numericality => { :greater_than_or_equal_to => 1 }
  before_validation :calculate_price

  private
    def calculate_price
      self.price = self.product.gross_price * self.amount
    end
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  attr_accessible :name
  has_one :order
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :producer
  attr_accessible :availability, :gross_price, :name, :net_price, :description, :category_id, :producer_id
  attr_accessible :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  before_validation :calculate_gross_price

  private
    def calculate_gross_price
      self.gross_price = self.net_price * (1.0 + Settings.vat_percent)
    end

  self.per_page = 2
end

app/models/role.rb
class Role < ActiveRecord::Base
  scopify

  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/settings.rb
class Settings < RailsSettings::CachedSettings
	attr_accessible :var
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessible :date_of_birth, :first_name, :last_name, :newsletter, :telephone_number
  has_one :profile
  has_many :addresses
  has_one :basket
  has_many :orders
  validate :user_must_be_adult
  validates_format_of :telephone_number, :with => /(\d{9})|(\+\d{11})/

  private
    def user_must_be_adult
      if self.date_of_birth > Date.today - 18.years
        errors.add(:date_of_birth, 'must be adult')
      end
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @baskets }
    end
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
    @basket = Basket.find(params[:id])
    @order_positions = @basket.order_positions.paginate(:page => params[:page])
    session[:return_to] ||= basket_path(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @basket }
    end
  end

  # GET /baskets/new
  # GET /baskets/new.json
  def new
    @basket = Basket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @basket }
    end
  end

  # GET /baskets/1/edit
  def edit
    @basket = Basket.find(params[:id])
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(params[:basket])

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render json: @basket, status: :created, location: @basket }
      else
        format.html { render action: "new" }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /baskets/1
  # PUT /baskets/1.json
  def update
    @basket = Basket.find(params[:id])

    respond_to do |format|
      if @basket.update_attributes(params[:basket])
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket = Basket.find(params[:id])
    @basket.destroy

    respond_to do |format|
      format.html { redirect_to baskets_url }
      format.json { head :no_content }
    end
  end

  def add_to_basket
    current_user.basket.add_to_basket(params[:product_id])
    redirect_to :back
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/baskets/_form.html.erb
<%= form_for @basket, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                baskets_path, :class => 'btn' %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<%- model_class = Basket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/baskets/index.html.erb
<%- model_class = Basket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= link_to basket.id, basket_path(basket) %></td>
        <td><%= basket.user_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_basket_path(basket), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      basket_path(basket),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_basket_path,
            :class => 'btn btn-primary' %>

app/views/baskets/new.html.erb
<%- model_class = Basket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/baskets/show.html.erb
<%- model_class = Basket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<% if admin? %>
  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                baskets_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_basket_path(@basket), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                basket_path(@basket),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>
<% else %>
    <% unless @basket.order_positions.empty? %>
      <%= render :template => 'order_positions/index_items' %>
      <%= link_to 'Checkout', new_order_path, :class => 'btn btn-primary' %>
    <% else %>
      Your basket is empty.
    <% end %>
<% end %>