config/routes.rb
Shop::Application.routes.draw do
  root :to => 'home#index'

  get 'home/index'
  get 'about/index'
  get 'contact/index'

  post 'add_to_basket/:product_id' => 'baskets#add_to_basket', :as => 'add_to_basket'

  resources :orders
  resources :products
  resources :baskets
  resources :order_positions
  resources :producers
  resources :categories
  resources :payment_methods
  resources :deliveries
  resources :addresses
  resources :countries

  devise_for :users, :controllers => { :sessions => 'sessions' }
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    unless user.has_role? :admin
      unless user.new_record?
        can :manage, [Address, Basket, User, OrderPosition], :user_id => user.id
        can :manage, OrderPosition, :container_id => user.basket.id, :container_type => 'Basket'
        can [:create, :read], Order, :user_id => user.id
      end
      can :read, Category
      can :read, Product
    else
      can :manage, :all
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_one :order
  attr_accessible :address_line_1, :address_line_2, :city, :first_name, :last_name, :postal_code, :country_id, :user_id, :name
  validates :address_line_1, :city, :first_name, :last_name, :postal_code, :country_id, :user_id, :name, :presence => true
  validates_format_of :postal_code, :with => /\d{2}\-\d{3}/
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  has_many :order_positions, :as => :container

  def add_to_basket(product_id)
    op = OrderPosition.where(:product_id => product_id, :container_id => self.id, :container_type => 'Basket').first
    if op.nil?
      op = OrderPosition.new
      op.product_id = product_id
      op.container = self
      op.amount = 1;
      op.price = Product.find(product_id).gross_price
    else
      op.amount += 1
      op.price += Product.find(product_id).gross_price
    end
    op.save
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  acts_as_nested_set
  has_many :products
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  has_many :addresses
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :cost, :name
  has_one :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :address
  belongs_to :delivery
  belongs_to :payment_method
  belongs_to :user
  has_many :order_positions, :as => :container
  attr_accessible :delivery_cost, :status, :value, :address_id, :delivery_id, :payment_method_id
  validate :available
  validates :address_id, :presence => true

  private
    def available
      order_positions.each do |op|
        if op.amount > op.product.availability
          errors.add(:base, 'order positions must be available')
        end
      end
    end
end

app/models/order_position.rb
class OrderPosition < ActiveRecord::Base
  belongs_to :product
  belongs_to :container, :polymorphic => true
  attr_accessible :amount, :price
  validates :amount, :numericality => { :greater_than_or_equal_to => 1 }
  before_validation :calculate_price

  private
    def calculate_price
      self.price = self.product.gross_price * self.amount
    end
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  attr_accessible :name
  has_one :order
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :producer
  attr_accessible :availability, :gross_price, :name, :net_price, :description, :category_id, :producer_id
  attr_accessible :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  before_validation :calculate_gross_price

  private
    def calculate_gross_price
      self.gross_price = self.net_price * (1.0 + Settings.vat_percent)
    end

  self.per_page = 2
end

app/models/role.rb
class Role < ActiveRecord::Base
  scopify

  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/settings.rb
class Settings < RailsSettings::CachedSettings
	attr_accessible :var
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessible :date_of_birth, :first_name, :last_name, :newsletter, :telephone_number
  has_one :profile
  has_many :addresses
  has_one :basket
  has_many :orders
  validate :user_must_be_adult
  validates_format_of :telephone_number, :with => /(\d{9})|(\+\d{11})/

  private
    def user_must_be_adult
      if self.date_of_birth > Date.today - 18.years
        errors.add(:date_of_birth, 'must be adult')
      end
    end
end

app/controllers/order_positions_controller.rb
class OrderPositionsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /order_positions
  # GET /order_positions.json
  def index
    @order_positions = OrderPosition.all
    session[:return_to] ||= order_positions_url

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_positions }
    end
  end

  # GET /order_positions/1
  # GET /order_positions/1.json
  def show
    @order_position = OrderPosition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_position }
    end
  end

  # GET /order_positions/new
  # GET /order_positions/new.json
  def new
    @order_position = OrderPosition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_position }
    end
  end

  # GET /order_positions/1/edit
  def edit
    @order_position = OrderPosition.find(params[:id])
  end

  # POST /order_positions
  # POST /order_positions.json
  def create
    @order_position = OrderPosition.new(params[:order_position])

    respond_to do |format|
      if @order_position.save
        format.html { redirect_to @order_position, notice: 'Order position was successfully created.' }
        format.json { render json: @order_position, status: :created, location: @order_position }
      else
        format.html { render action: "new" }
        format.json { render json: @order_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /order_positions/1
  # PUT /order_positions/1.json
  def update
    @order_position = OrderPosition.find(params[:id])

    respond_to do |format|
      if @order_position.update_attributes(params[:order_position])
        format.html { redirect_to session[:return_to], notice: 'Order position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_positions/1
  # DELETE /order_positions/1.json
  def destroy
    @order_position = OrderPosition.find(params[:id])
    @order_position.destroy

    respond_to do |format|
      format.html { redirect_to order_positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_positions_helper.rb
module OrderPositionsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/order_positions/_form.html.erb
<%- model_class = OrderPosition -%>
<%= form_for @order_position, :html => { :class => 'form-horizontal' } do |f| %>
  <% if admin? %>
    <div class="control-group">
      <%= f.label :product_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :product_id, Product.all, :id, :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :price, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :price, :class => 'number_field' %>
      </div>
    </div>
  <% else %>
    <dl class="dl-horizontal">
      <dt><strong><%= Product.human_attribute_name(:image) %>:</strong></dt>
      <dd><%= image_tag @order_position.product.image.url %></dd>
      <dt><strong><%= Product.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @order_position.product.name %></dd>
      <dt><strong><%= Product.human_attribute_name(:net_price) %>:</strong></dt>
      <dd><%= @order_position.product.net_price %></dd>
      <dt><strong><%= Product.human_attribute_name(:gross_price) %>:</strong></dt>
      <dd><%= @order_position.product.gross_price %></dd>
      <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
      <dd><%= @order_position.price %></dd>
    </dl>
  <% end %>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :amount, :class => 'number_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                order_positions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/order_positions/edit.html.erb
<%- model_class = OrderPosition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/order_positions/index.html.erb
<%- model_class = OrderPosition -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if admin? %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @order_positions.each do |order_position| %>
      <tr>
        <td><%= link_to order_position.id, order_position_path(order_position) %></td>
        <td><%= order_position.product_id %></td>
        <td><%= order_position.price %></td>
        <td><%= order_position.amount %></td>
        <td><%=l order_position.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_order_position_path(order_position), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      order_position_path(order_position),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_order_position_path,
              :class => 'btn btn-primary' %>
<% else %>
  <%= render :template => 'order_positions/index_items' %>
<% end %>

app/views/order_positions/index_items.html.erb
<%- model_class = OrderPosition -%>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= Product.human_attribute_name(:image) %></th>
    <th><%= Product.human_attribute_name(:name) %></th>
    <th><%= Product.human_attribute_name(:net_price) %></th>
    <th><%= Product.human_attribute_name(:gross_price) %></th>
    <th><%= model_class.human_attribute_name(:amount) %></th>
    <th><%= model_class.human_attribute_name(:price) %></th>
    <% unless defined?(show) and show %>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @order_positions.each do |order_position| %>
    <tr>
      <td><%= image_tag order_position.product.image.url(:thumb) %></td>
      <td><%= order_position.product.name %></td>
      <td><%= number_to_currency2(order_position.product.net_price) %></td>
      <td><%= number_to_currency2(order_position.product.gross_price) %></td>
      <td><%= order_position.amount %></td>
      <td><%= number_to_currency2(order_position.price) %></td>
      <% unless defined?(show) and show %>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_order_position_path(order_position), :class => 'btn btn-mini' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    order_position_path(order_position),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini btn-danger' %>
      </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/order_positions/new.html.erb
<%- model_class = OrderPosition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/order_positions/show.html.erb
<%- model_class = OrderPosition -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @order_position.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @order_position.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @order_position.amount %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              order_positions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_position_path(@order_position), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_position_path(@order_position),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>