config/routes.rb
Shop::Application.routes.draw do
  root :to => 'home#index'

  get 'home/index'
  get 'about/index'
  get 'contact/index'

  post 'add_to_basket/:product_id' => 'baskets#add_to_basket', :as => 'add_to_basket'

  resources :orders
  resources :products
  resources :baskets
  resources :order_positions
  resources :producers
  resources :categories
  resources :payment_methods
  resources :deliveries
  resources :addresses
  resources :countries

  devise_for :users, :controllers => { :sessions => 'sessions' }
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    unless user.has_role? :admin
      unless user.new_record?
        can :manage, [Address, Basket, User, OrderPosition], :user_id => user.id
        can :manage, OrderPosition, :container_id => user.basket.id, :container_type => 'Basket'
        can [:create, :read], Order, :user_id => user.id
      end
      can :read, Category
      can :read, Product
    else
      can :manage, :all
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_one :order
  attr_accessible :address_line_1, :address_line_2, :city, :first_name, :last_name, :postal_code, :country_id, :user_id, :name
  validates :address_line_1, :city, :first_name, :last_name, :postal_code, :country_id, :user_id, :name, :presence => true
  validates_format_of :postal_code, :with => /\d{2}\-\d{3}/
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  has_many :order_positions, :as => :container

  def add_to_basket(product_id)
    op = OrderPosition.where(:product_id => product_id, :container_id => self.id, :container_type => 'Basket').first
    if op.nil?
      op = OrderPosition.new
      op.product_id = product_id
      op.container = self
      op.amount = 1;
      op.price = Product.find(product_id).gross_price
    else
      op.amount += 1
      op.price += Product.find(product_id).gross_price
    end
    op.save
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  acts_as_nested_set
  has_many :products
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  has_many :addresses
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :cost, :name
  has_one :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :address
  belongs_to :delivery
  belongs_to :payment_method
  belongs_to :user
  has_many :order_positions, :as => :container
  attr_accessible :delivery_cost, :status, :value, :address_id, :delivery_id, :payment_method_id
  validate :available
  validates :address_id, :presence => true

  private
    def available
      order_positions.each do |op|
        if op.amount > op.product.availability
          errors.add(:base, 'order positions must be available')
        end
      end
    end
end

app/models/order_position.rb
class OrderPosition < ActiveRecord::Base
  belongs_to :product
  belongs_to :container, :polymorphic => true
  attr_accessible :amount, :price
  validates :amount, :numericality => { :greater_than_or_equal_to => 1 }
  before_validation :calculate_price

  private
    def calculate_price
      self.price = self.product.gross_price * self.amount
    end
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  attr_accessible :name
  has_one :order
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :producer
  attr_accessible :availability, :gross_price, :name, :net_price, :description, :category_id, :producer_id
  attr_accessible :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  before_validation :calculate_gross_price

  private
    def calculate_gross_price
      self.gross_price = self.net_price * (1.0 + Settings.vat_percent)
    end

  self.per_page = 2
end

app/models/role.rb
class Role < ActiveRecord::Base
  scopify

  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/settings.rb
class Settings < RailsSettings::CachedSettings
	attr_accessible :var
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessible :date_of_birth, :first_name, :last_name, :newsletter, :telephone_number
  has_one :profile
  has_many :addresses
  has_one :basket
  has_many :orders
  validate :user_must_be_adult
  validates_format_of :telephone_number, :with => /(\d{9})|(\+\d{11})/

  private
    def user_must_be_adult
      if self.date_of_birth > Date.today - 18.years
        errors.add(:date_of_birth, 'must be adult')
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    if admin?
      @products = Product.all
    else
      @products = Product.paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_client_view_index.html.erb
<%- model_class = Product -%>
<div class="row-fluid">
  <div class="span12">
  <% products.each do |product| %>
      <h2><%= product.name %></h2><br>
      <div class="row-fluid">
        <div class="span6">
          <%= image_tag product.image.url(:medium) %>
        </div>
        <div class="span6">
          <b><%= model_class.human_attribute_name(:category_id) + ':' %></b>
          <%= link_to Category.find(product.category_id).name, category_path(product.category_id) %><br>
          <b><%= model_class.human_attribute_name(:producer_id) + ':' %></b>
          <%= link_to Producer.find(product.producer_id).name, producer_path(product.producer_id) %><br>
          <b><%= model_class.human_attribute_name(:availability) + ':' %></b>
          <%= product.availability %><br>
          <b><%= model_class.human_attribute_name(:net_price) + ':' %></b>
          <%= number_to_currency2(product.net_price) %><br>
          <b><%= model_class.human_attribute_name(:gross_price) + ':' %></b>
          <%= number_to_currency2(product.gross_price) %><br>
          <br>
          <% if product.availability > 0 %>
            <%= link_to 'Add to basket', add_to_basket_path(:product_id => product.id), :method => :post, :class => 'btn btn-primary' %>
          <% else %>
            Product unavailable
          <% end %>
        </div>
      </div>
      <b><%= model_class.human_attribute_name(:description) + ':' %></b><br>
      <%= product.description %>
      <hr>
  <% end %>
  </div>
  <div class="row-fluid">
    <div class="span6 offset3">
      <%= will_paginate products %>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :category_id, Category.all, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field', :rows => 3 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :producer_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :producer_id, Producer.all, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :availability, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :availability, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :net_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :net_price, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if admin? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:category_id) %></th>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:producer_id) %></th>
        <th><%= model_class.human_attribute_name(:availability) %></th>
        <th><%= model_class.human_attribute_name(:net_price) %></th>
        <th><%= model_class.human_attribute_name(:gross_price) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.id, product_path(product) %></td>
          <td><%= link_to Category.find(product.category_id).name, category_path(product.category_id) %></td>
          <td><%= product.name %></td>
          <td><%= link_to Producer.find(product.producer_id).name, producer_path(product.producer_id) %></td>
          <td><%= product.availability %></td>
          <td><%= number_to_currency2(product.net_price) %></td>
          <td><%= number_to_currency2(product.gross_price) %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_product_path(product), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        product_path(product),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_product_path,
              :class => 'btn btn-primary' %>
<% else %>
 <%= render :partial => 'client_view_index', :locals => { :products => @products } %>
<% end %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dd><%= image_tag @product.image.url(:medium) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= link_to Category.find(@product.category_id).name, category_path(@product.category_id) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:producer_id) %>:</strong></dt>
  <dd><%= link_to Producer.find(@product.producer_id).name, producer_path(@product.producer_id) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:availability) %>:</strong></dt>
  <dd><%= @product.availability %></dd>
  <dt><strong><%= model_class.human_attribute_name(:net_price) %>:</strong></dt>
  <dd><%= number_to_currency2(@product.net_price) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gross_price) %>:</strong></dt>
  <dd><%= number_to_currency2(@product.gross_price) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <% if admin? %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_product_path(@product), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                product_path(@product),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Add to basket', add_to_basket_path(:product_id => @product.id), :method => :post, :class => 'btn btn-primary' %>
  <% end %>
</div>